name: Sync Documentation

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3


    - name: Verify temp directory contents
      run: |
        cd ../
        ls -l
        git clone https://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@github.com/raphaeldemonchy/myMkDoc.git
        ls -l
      working-directory: ${{ github.workspace }}

    - name: Copy documentation files to public repo
      run: |
        ls -l
        cp -r DOC-WIKI/* ../myMkDoc/docs/
        cd ../
        cd myMkDoc
        cd docs
        ls -l
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes to public repo
      run: |
        git config user.name "raphael"
        git config user.email "raphael.de-monchy@epitech.eu"
        git add .
        git commit -m "Sync documentation"
      working-directory: ${{ github.workspace }}

    - name: Push changes to public repo
      run: |
        git push https://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@github.com/raphaeldemonchy/myMkDoc.git main
      working-directory: ${{ github.workspace }}

