name: Sync Documentation

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Copy documentation files to public repo
      run: |
        mkdir -p ../docs_public
        cp -r DOC-WIKI/* ../docs_public
      working-directory: ${{ github.workspace }}

    - name: Verify temp directory contents
      run: |
        cd ../
        ls -l
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes to public repo
      run: |
        ls -l
        cd ../
        ls -l
        cd docs_public
        ls -l
        git init
        git config user.name "raphael"
        git config user.email "raphael.de-monchy@epitech.eu"
        git add .
        git commit -m "Sync documentation"
        git branch -m main
      working-directory: ${{ github.workspace }}

    - name: Push changes to public repo
      run: |
        cd docs_public
        git push https://${{ secrets.GITHUB_TOKEN }}git@github.com:raphaeldemonchy/myMkDoc.git main
      working-directory: ${{ github.workspace }}

